### ISSUE TITLE
openwrt: new dependency issue

### ISSUE THREAD

**Issue by wfleurant** [MassMesh/mm-cli#6]
re: 799e7ea080c687fa2fa5f6e6286887dbc5d06c6f

when running `python3 -m mm_cli`  
we do not include pkg_resources in OpenWrt (setuptools ?)
``` 
  File "/usr/lib/python3.8/site-packages/mm_cli/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution
```

where `__init__.py` is  

```
from pkg_resources import get_distribution
__version__ = get_distribution('mm-cli').version
```

**Comment by wfleurant** [comment]
when i add `python3-setuptools` https://github.com/MassMesh/meta-imagebuilder/commit/6a5b65346cbe0a3273eae4447e17f63ee9e28088  

this error is on rpi3

```
root@OpenWrt:/tmp# opkg list | grep mm-cl
python3-mm-cli-src - 0.0.5-5
root@OpenWrt:/tmp# mm
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
  File "/usr/lib/python3.8/site-packages/mm_cli/__init__.py", line 3, in <module>
    __version__ = get_distribution('mm-cli').version
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 357, in get_provider
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'mm-cli' distribution was not found and is required by the application
```
